# Generated by Django 6.0.2 on 2026-03-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('corro', models.EmailField(max_length=254)),
                ('edad', models.IntegerField()),
            ],
        ),
    ]
