# Generated by Django 6.0.2 on 2026-03-02 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='corro',
            new_name='correo',
        ),
    ]
